/* Generated by scripts/generate-pixel-sprites.py. Do not edit by hand.
 * Source: assets/pixel/fx_snow.pxart */

#include "lvgl.h"

static const uint8_t fx_snow_0_map[] = {
    0x00, 0x00, 0x3f, 0xbf, 0x00, 0x00, 0x3f, 0xbf, 0x9e, 0xef, 0x3f, 0xbf,
    0x00, 0x00, 0x3f, 0xbf, 0x00, 0x00, 0x00, 0xff, 0x00, 0xff, 0xff, 0xff,
    0x00, 0xff, 0x00,
};

const lv_image_dsc_t fx_snow_0 = {
    .header.magic = LV_IMAGE_HEADER_MAGIC,
    .header.cf = LV_COLOR_FORMAT_RGB565A8,
    .header.flags = 0,
    .header.w = 3,
    .header.h = 3,
    .header.stride = 6,
    .header.reserved_2 = 0,
    .data_size = sizeof(fx_snow_0_map),
    .data = fx_snow_0_map,
};

static const uint8_t fx_snow_1_map[] = {
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x9e, 0xef, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xff, 0x00,
    0x00, 0x00, 0x00,
};

const lv_image_dsc_t fx_snow_1 = {
    .header.magic = LV_IMAGE_HEADER_MAGIC,
    .header.cf = LV_COLOR_FORMAT_RGB565A8,
    .header.flags = 0,
    .header.w = 3,
    .header.h = 3,
    .header.stride = 6,
    .header.reserved_2 = 0,
    .data_size = sizeof(fx_snow_1_map),
    .data = fx_snow_1_map,
};
