/* Generated by scripts/generate-pixel-sprites.py. Do not edit by hand. */

#pragma once

#include "lvgl.h"

LV_IMAGE_DECLARE(actor_blink);

LV_IMAGE_DECLARE(actor_idle_0);
LV_IMAGE_DECLARE(actor_idle_1);
#define ACTOR_IDLE_FRAME_COUNT 2
/* Frame list for lv_animimg_set_src(); must stay static. */
#define ACTOR_IDLE_FRAMES { &actor_idle_0, &actor_idle_1 }

LV_IMAGE_DECLARE(actor_look_0);
LV_IMAGE_DECLARE(actor_look_1);
LV_IMAGE_DECLARE(actor_look_2);
LV_IMAGE_DECLARE(actor_look_3);
#define ACTOR_LOOK_FRAME_COUNT 4
/* Frame list for lv_animimg_set_src(); must stay static. */
#define ACTOR_LOOK_FRAMES { &actor_look_0, &actor_look_1, &actor_look_2, &actor_look_3 }

LV_IMAGE_DECLARE(actor_object_idle_0);
LV_IMAGE_DECLARE(actor_object_idle_1);
#define ACTOR_OBJECT_IDLE_FRAME_COUNT 2
/* Frame list for lv_animimg_set_src(); must stay static. */
#define ACTOR_OBJECT_IDLE_FRAMES { &actor_object_idle_0, &actor_object_idle_1 }

LV_IMAGE_DECLARE(actor_object_walk_0);
LV_IMAGE_DECLARE(actor_object_walk_1);
LV_IMAGE_DECLARE(actor_object_walk_2);
LV_IMAGE_DECLARE(actor_object_walk_3);
#define ACTOR_OBJECT_WALK_FRAME_COUNT 4
/* Frame list for lv_animimg_set_src(); must stay static. */
#define ACTOR_OBJECT_WALK_FRAMES { &actor_object_walk_0, &actor_object_walk_1, &actor_object_walk_2, &actor_object_walk_3 }

LV_IMAGE_DECLARE(actor_paw_0);
LV_IMAGE_DECLARE(actor_paw_1);
LV_IMAGE_DECLARE(actor_paw_2);
LV_IMAGE_DECLARE(actor_paw_3);
#define ACTOR_PAW_FRAME_COUNT 4
/* Frame list for lv_animimg_set_src(); must stay static. */
#define ACTOR_PAW_FRAMES { &actor_paw_0, &actor_paw_1, &actor_paw_2, &actor_paw_3 }

LV_IMAGE_DECLARE(actor_sit_0);
LV_IMAGE_DECLARE(actor_sit_1);
LV_IMAGE_DECLARE(actor_sit_2);
LV_IMAGE_DECLARE(actor_sit_3);
#define ACTOR_SIT_FRAME_COUNT 4
/* Frame list for lv_animimg_set_src(); must stay static. */
#define ACTOR_SIT_FRAMES { &actor_sit_0, &actor_sit_1, &actor_sit_2, &actor_sit_3 }

LV_IMAGE_DECLARE(actor_sleep_0);
LV_IMAGE_DECLARE(actor_sleep_1);
#define ACTOR_SLEEP_FRAME_COUNT 2
/* Frame list for lv_animimg_set_src(); must stay static. */
#define ACTOR_SLEEP_FRAMES { &actor_sleep_0, &actor_sleep_1 }

LV_IMAGE_DECLARE(actor_walk_0);
LV_IMAGE_DECLARE(actor_walk_1);
LV_IMAGE_DECLARE(actor_walk_2);
LV_IMAGE_DECLARE(actor_walk_3);
#define ACTOR_WALK_FRAME_COUNT 4
/* Frame list for lv_animimg_set_src(); must stay static. */
#define ACTOR_WALK_FRAMES { &actor_walk_0, &actor_walk_1, &actor_walk_2, &actor_walk_3 }

LV_IMAGE_DECLARE(env_cloud);

LV_IMAGE_DECLARE(env_hill);

LV_IMAGE_DECLARE(env_hill_near);

LV_IMAGE_DECLARE(env_moon_0);
LV_IMAGE_DECLARE(env_moon_1);
LV_IMAGE_DECLARE(env_moon_2);
LV_IMAGE_DECLARE(env_moon_3);
LV_IMAGE_DECLARE(env_moon_4);
LV_IMAGE_DECLARE(env_moon_5);
LV_IMAGE_DECLARE(env_moon_6);
LV_IMAGE_DECLARE(env_moon_7);
#define ENV_MOON_FRAME_COUNT 8
/* Frame list for lv_animimg_set_src(); must stay static. */
#define ENV_MOON_FRAMES { &env_moon_0, &env_moon_1, &env_moon_2, &env_moon_3, &env_moon_4, &env_moon_5, &env_moon_6, &env_moon_7 }

LV_IMAGE_DECLARE(env_sky_dawn);

LV_IMAGE_DECLARE(env_sky_day);

LV_IMAGE_DECLARE(env_sky_dusk);

LV_IMAGE_DECLARE(env_sky_night);

LV_IMAGE_DECLARE(env_sun_0);
LV_IMAGE_DECLARE(env_sun_1);
LV_IMAGE_DECLARE(env_sun_2);
LV_IMAGE_DECLARE(env_sun_3);
#define ENV_SUN_FRAME_COUNT 4
/* Frame list for lv_animimg_set_src(); must stay static. */
#define ENV_SUN_FRAMES { &env_sun_0, &env_sun_1, &env_sun_2, &env_sun_3 }

LV_IMAGE_DECLARE(fx_cool_wave_0);
LV_IMAGE_DECLARE(fx_cool_wave_1);
#define FX_COOL_WAVE_FRAME_COUNT 2
/* Frame list for lv_animimg_set_src(); must stay static. */
#define FX_COOL_WAVE_FRAMES { &fx_cool_wave_0, &fx_cool_wave_1 }

LV_IMAGE_DECLARE(fx_light_cone);

LV_IMAGE_DECLARE(fx_rain_0);
LV_IMAGE_DECLARE(fx_rain_1);
#define FX_RAIN_FRAME_COUNT 2
/* Frame list for lv_animimg_set_src(); must stay static. */
#define FX_RAIN_FRAMES { &fx_rain_0, &fx_rain_1 }

LV_IMAGE_DECLARE(fx_rune_0);
LV_IMAGE_DECLARE(fx_rune_1);
#define FX_RUNE_FRAME_COUNT 2
/* Frame list for lv_animimg_set_src(); must stay static. */
#define FX_RUNE_FRAMES { &fx_rune_0, &fx_rune_1 }

LV_IMAGE_DECLARE(fx_scanline);

LV_IMAGE_DECLARE(fx_smoke_0);
LV_IMAGE_DECLARE(fx_smoke_1);
LV_IMAGE_DECLARE(fx_smoke_2);
#define FX_SMOKE_FRAME_COUNT 3
/* Frame list for lv_animimg_set_src(); must stay static. */
#define FX_SMOKE_FRAMES { &fx_smoke_0, &fx_smoke_1, &fx_smoke_2 }

LV_IMAGE_DECLARE(fx_snow_0);
LV_IMAGE_DECLARE(fx_snow_1);
#define FX_SNOW_FRAME_COUNT 2
/* Frame list for lv_animimg_set_src(); must stay static. */
#define FX_SNOW_FRAMES { &fx_snow_0, &fx_snow_1 }

LV_IMAGE_DECLARE(fx_sparkle_0);
LV_IMAGE_DECLARE(fx_sparkle_1);
LV_IMAGE_DECLARE(fx_sparkle_2);
#define FX_SPARKLE_FRAME_COUNT 3
/* Frame list for lv_animimg_set_src(); must stay static. */
#define FX_SPARKLE_FRAMES { &fx_sparkle_0, &fx_sparkle_1, &fx_sparkle_2 }

LV_IMAGE_DECLARE(fx_splash_0);
LV_IMAGE_DECLARE(fx_splash_1);
#define FX_SPLASH_FRAME_COUNT 2
/* Frame list for lv_animimg_set_src(); must stay static. */
#define FX_SPLASH_FRAMES { &fx_splash_0, &fx_splash_1 }

LV_IMAGE_DECLARE(hud_digits_0);
LV_IMAGE_DECLARE(hud_digits_1);
LV_IMAGE_DECLARE(hud_digits_2);
LV_IMAGE_DECLARE(hud_digits_3);
LV_IMAGE_DECLARE(hud_digits_4);
LV_IMAGE_DECLARE(hud_digits_5);
LV_IMAGE_DECLARE(hud_digits_6);
LV_IMAGE_DECLARE(hud_digits_7);
LV_IMAGE_DECLARE(hud_digits_8);
LV_IMAGE_DECLARE(hud_digits_9);
LV_IMAGE_DECLARE(hud_digits_10);
#define HUD_DIGITS_FRAME_COUNT 11
/* Frame list for lv_animimg_set_src(); must stay static. */
#define HUD_DIGITS_FRAMES { &hud_digits_0, &hud_digits_1, &hud_digits_2, &hud_digits_3, &hud_digits_4, &hud_digits_5, &hud_digits_6, &hud_digits_7, &hud_digits_8, &hud_digits_9, &hud_digits_10 }

LV_IMAGE_DECLARE(pet_idle_0);
LV_IMAGE_DECLARE(pet_idle_1);
#define PET_IDLE_FRAME_COUNT 2
/* Frame list for lv_animimg_set_src(); must stay static. */
#define PET_IDLE_FRAMES { &pet_idle_0, &pet_idle_1 }

LV_IMAGE_DECLARE(room_bedroom);

LV_IMAGE_DECLARE(room_entry);

LV_IMAGE_DECLARE(room_guest);

LV_IMAGE_DECLARE(room_kitchen);

LV_IMAGE_DECLARE(room_living);

LV_IMAGE_DECLARE(room_study);
